Repository codeit-sprint6-team14/Global-Nomad, pull requests merged in 2024-08, with the labels that each got.

#30 Refactor: Calender 리팩토링
  src/components/Calendar/body.tsx
  src/components/Calendar/header.tsx
  src/components/Calendar/index.tsx
  src/constants/date.ts
  src/types/calendarTypes.ts
Labels: Refactor

#33 Refactor: Floating Box 리팩토링
  src/components/FloatingBox/DesktopComponents/header.tsx
  src/components/FloatingBox/DesktopComponents/index.ts
  src/components/FloatingBox/DesktopComponents/priceInfo.tsx
  src/components/FloatingBox/DesktopComponents/timeSlotSelection.tsx
  src/components/FloatingBox/desktop.tsx
Labels: Refactor

#19 Design: Search 공통 컴포넌트 UI 구현
  public/images/icon-search.svg
  src/components/Cards/components/cardButton.tsx
  src/components/Search/index.tsx
Labels: Feat, Refactor, Design

#23 Design: 예약 정보 모달 UI 구현
  public/images/icon-close.svg
  src/components/ReservationInfoModal/components/reservationCard.tsx
  src/components/ReservationInfoModal/components/tabButton.tsx
  src/components/ReservationInfoModal/index.tsx
  tailwind.config.ts
Labels: Design

#35 Test: 공통 컴포넌트 Storybook 적용
  .storybook/main.ts
  .storybook/preview.ts
  src/components/Calendar/index.tsx
  src/components/Counter/index.tsx
  src/components/Dropdown/dropDownOption.tsx
  src/mockData/availableSchedule.js
  src/stories/Button.stories.ts
  src/stories/Button.tsx
  src/stories/Button/categoryButton.stories.tsx
  src/stories/Button/defaultButton.stories.tsx
  src/stories/Calendar/calendar.stories.tsx
  src/stories/Chip/chip.stories.tsx
  src/stories/Configure.mdx
  src/stories/Counter/counter.stories.tsx
  src/stories/DropDown/dropDown.stories.tsx
  src/stories/FloatingBox/desktop.stories.tsx
  src/stories/FloatingBox/mobile.stories.tsx
  src/stories/FloatingBox/tablet.stories.tsx
  src/stories/Header.stories.ts
  src/stories/Header.tsx
  src/stories/Modal/dateSelectModal.stories.tsx
  src/stories/Page.stories.ts
  src/stories/Page.tsx
  src/stories/assets/accessibility.png
  src/stories/assets/accessibility.svg
  src/stories/assets/addon-library.png
  src/stories/assets/assets.png
  src/stories/assets/avif-test-image.avif
  src/stories/assets/context.png
  src/stories/assets/discord.svg
  src/stories/assets/docs.png
  src/stories/assets/figma-plugin.png
  src/stories/assets/github.svg
  src/stories/assets/share.png
  src/stories/assets/styling.png
  src/stories/assets/testing.png
  src/stories/assets/theming.png
  src/stories/assets/tutorials.svg
  src/stories/assets/youtube.svg
  src/stories/button.css
  src/stories/header.css
  src/stories/page.css
Labels: Test

#36 Test: 공통 컴포넌트 storybook 적용 및 build 에러 수정
  .storybook/preview.ts
  src/components/Cards/myActivityCard.tsx
  src/components/Cards/myActivityCardList.tsx
  src/components/Cards/reservationCard.tsx
  src/components/Cards/reservationCardList.tsx
  src/components/Modal/Review/index.tsx
  src/components/ReservationInfoModal/index.tsx
  src/components/SideNavMenu/sideNavMenuOption.tsx
  src/mockData/myActivityCardsData.ts
  src/mockData/reservationCardsData.ts
  src/stories/Cards/myActivityCard.stories.tsx
  src/stories/Cards/reservationCard.stories.tsx
  src/stories/Input/dropdownInput.stories.tsx
  src/stories/Modal/reviewModal.stories.tsx
  src/types/cardDataList.ts
  src/types/sideNavMenuTypes.ts
Labels: Chore, Test

#40 Feat: 체험 상세 페이지 UI 및 API 작업
  next.config.mjs
  package-lock.json
  package.json
  public/assets/icons/map.svg
  src/apis/dummy.txt
  src/apis/getActivity.ts
  src/components/common/Cards/index.tsx
  src/components/common/Cards/myActivityCard.tsx
  src/components/common/Cards/reservationCard.tsx
  src/components/common/FloatingBox/mobile.tsx
  src/components/common/FloatingBox/tablet.tsx
  src/components/common/NavBar/index.tsx
  src/components/pages/activity-details/activity-information.tsx
  src/components/pages/activity-details/banner-image.tsx
  src/components/pages/activity-details/description.tsx
  src/components/pages/activity-details/header.tsx
  src/components/pages/activity-details/kakao-map.tsx
  src/components/pages/activity-details/review-list.tsx
  src/components/pages/activity-details/review.tsx
  src/components/pages/dummy.txt
  src/hooks/useViewportSize.tsx
  src/libs/dummy.txt
  src/mockData/reviewList.js
  src/pages/_app.tsx
  src/pages/_document.tsx
  src/pages/activities/[activity-id]/index.tsx
  src/pages/activities/index.tsx
  src/types/activity.ts
  src/types/activityReviews.ts
  tsconfig.json
Labels: Feat

#41 Design: 내정보 페이지 디자인
  public/assets/icons/facebook.svg
  public/assets/icons/instagram.svg
  public/assets/icons/left-arrow.svg
  public/assets/icons/rating.svg
  public/assets/icons/twitter.svg
  public/assets/icons/youtube.svg
  public/svgs/icon-facebook.svg
  public/svgs/icon-instagram.svg
  public/svgs/icon-twitter.svg
  public/svgs/icon-youtube.svg
  public/svgs/star.svg
  src/components/common/CardResource/rating.tsx
  src/components/common/Footer/index.tsx
  src/components/common/SideNavMenu/index.tsx
  src/components/common/SideNavMenu/menuOptionList.tsx
  src/components/common/SideNavMenu/sideNavMenuOptionList.tsx
  src/components/pages/myPage/inputSection.tsx
  src/components/pages/myPage/myProfile.tsx
  src/components/pages/myPage/passwordInputSection.tsx
  src/pages/_app.tsx
  src/pages/my-page/index.tsx
  src/pages/my-page/profile.tsx
Labels: Design

#43 [FP-34] Design: popup 구현
  public/assets/icons/check.svg
  src/components/common/Modal/CancelConfirm/index.tsx
  src/components/common/Modal/RegisterConfirm/index.tsx
  src/components/common/Modal/index.ts
Labels: Design

#44 Design: 예약 내역 페이지 UI 구현
  public/assets/icons/add-button.svg
  public/assets/icons/ic-check.svg
  public/assets/icons/next-button.svg
  public/assets/icons/paper.svg
  public/assets/icons/prev-button.svg
  public/assets/icons/subtract-button.svg
  src/components/common/Calendar/header.tsx
  src/components/common/Cards/components/cardFooter.tsx
  src/components/common/Cards/reservationCard.tsx
  src/components/common/Counter/index.tsx
  src/components/common/Dropdown/dropDownList.tsx
  src/components/common/Dropdown/dropDownOption.tsx
  src/components/common/Filter/index.tsx
  src/components/common/Modal/CancelReservation/index.tsx
  src/components/common/Modal/Overlay/index.tsx
  src/components/common/Modal/Review/header.tsx
  src/components/common/Modal/Review/index.tsx
  src/components/common/Modal/Review/textareaWithSubmit.tsx
  src/components/common/Modal/index.ts
  src/components/common/SideNavMenu/menuOptionList.tsx
  src/components/pages/myPage/ReservationList/emptyReservationContent.tsx
  src/components/pages/myPage/ReservationList/reservationCardList.tsx
  src/components/pages/myPage/ReservationList/reservationContent.tsx
  src/constants/deviceBreakpoints.ts
  src/hooks/useClickOutside.ts
  src/hooks/useDeviceState.ts
  src/hooks/useToggle.ts
  src/pages/_app.tsx
  src/pages/my-page/reservation-list.tsx
  src/store/dummy.txt
  src/store/modalAtom.ts
  src/stories/Filter/filter.stories.tsx
  src/stories/Modal/cancelReservation.stories.tsx
  src/stories/Pages/ReservationList/emptyReservationContent.stories.tsx
  src/stories/Pages/ReservationList/reservationList.stories.tsx
  src/types/deviceTypes.ts
Labels: Design

#42 Feat: 체험 상세 페이지 API에서 받아온 체험 장소에 따라 지도 위치 렌더링
  public/assets/icons/map-marker.svg
  public/assets/icons/pagination-left.svg
  public/assets/icons/pagination-right.svg
  src/apis/getActivity.ts
  src/components/common/FloatingBox/TabletComponents/main.tsx
  src/components/common/FloatingBox/desktop.tsx
  src/components/common/Modal/DateSelect/index.tsx
  src/components/common/Pagination/index.tsx
  src/components/pages/ActivityDetails/activityInformation.tsx
  src/components/pages/ActivityDetails/bannerImage.tsx
  src/components/pages/ActivityDetails/description.tsx
  src/components/pages/ActivityDetails/header.tsx
  src/components/pages/ActivityDetails/kakaoMap.tsx
  src/components/pages/ActivityDetails/review.tsx
  src/components/pages/ActivityDetails/reviewList.tsx
  src/components/pages/activity-details/kakao-map.tsx
  src/components/pages/activity-details/review-list.tsx
  src/mockData/reviewList.js
  src/pages/_document.tsx
  src/pages/activities/index.tsx
  src/types/activity.ts
  src/types/reviewList.ts
  src/utils/formatDate.ts
Labels: Feat

#46 Design: 로그인/회원가입 페이지 UI 구현
  package-lock.json
  package.json
  public/assets/icons/google.svg
  public/assets/icons/kakaotalk.svg
  public/assets/images/auth-logo.png
  src/components/common/Cards/reservationCard.tsx
  src/components/common/Input/PasswordInput.tsx
  src/components/common/Modal/index.ts
  src/components/pages/auth/signInForm.tsx
  src/components/pages/auth/signupForm.tsx
  src/components/pages/auth/socialForm.tsx
  src/constants/errorMessages.ts
  src/pages/_app.tsx
  src/pages/signin/index.tsx
  src/pages/signup/index.tsx
  src/types/formTypes.ts
  src/utils/schema.ts
Labels: Design

#47 Design: 예약 현황 페이지 UI
  package-lock.json
  package.json
  src/components/common/Chip/index.tsx
  src/components/common/ReservationInfoModal/components/reservationCard.tsx
  src/components/common/ReservationInfoModal/components/tabButton.tsx
  src/components/common/ReservationInfoModal/index.tsx
  src/components/pages/myPage/myProfile.tsx
  src/components/pages/myPageSchedule/calender.tsx
  src/components/pages/myPageSchedule/dateCell.tsx
  src/components/pages/myPageSchedule/mySchedule.tsx
  src/pages/my-page/schedule.tsx
  src/stories/Chip/chip.stories.tsx
Labels: Design

#48 Refactor: 체험 상세 페이지 리팩토링
  src/apis/activityDetails.ts
  src/components/common/Counter/index.tsx
  src/components/common/FloatingBox/DesktopComponents/timeSlotSelection.tsx
  src/components/common/FloatingBox/MobileComponents/dateInfo.tsx
  src/components/common/FloatingBox/TabletComponents/main.tsx
  src/components/common/FloatingBox/desktop.tsx
  src/components/common/FloatingBox/mobile.tsx
  src/components/common/Modal/DateSelect/footer.tsx
  src/components/common/Modal/DateSelect/header.tsx
  src/components/common/Modal/DateSelect/index.tsx
  src/components/common/Modal/DateSelect/timeSlotSelection.tsx
  src/components/pages/ActivityDetails/activityInformation.tsx
  src/components/pages/ActivityDetails/reviewList.tsx
  src/hooks/useActivityAvailableSchedule.tsx
  src/hooks/useReservationMutation.ts
  src/mockData/availableSchedule.js
  src/store/activityDetailsAtom.ts
  src/types/availableSchedulesTypes.ts
Labels: Refactor

#52 Design: 알림창 UI
  public/assets/icons/close.svg
  src/components/common/NavBar/Notification.tsx
  src/components/common/NavBar/index.tsx
  src/components/common/Popover/AlarmInfo/index.tsx
  src/components/common/Popover/Point/index.tsx
  src/components/common/Popover/PopoverContent.tsx
  src/components/common/Popover/PopoverRoot.tsx
  src/components/common/Popover/PopoverTrigger.tsx
  src/components/common/Popover/PopoverUI.tsx
  src/components/common/Popover/index.tsx
  src/components/common/ReservationInfoModal/index.tsx
  src/pages/_app.tsx
Labels: Design

#53 Refactor: 체험 상세 페이지 캘린더 리팩토링
  src/apis/activityDetails.ts
  src/components/common/Calendar/index.tsx
  src/components/common/Counter/index.tsx
  src/components/common/FloatingBox/DesktopComponents/priceInfo.tsx
  src/components/common/FloatingBox/DesktopComponents/totalPrice.tsx
  src/components/common/FloatingBox/MobileComponents/dateInfo.tsx
  src/components/common/FloatingBox/MobileComponents/priceInfo.tsx
  src/components/common/FloatingBox/TabletComponents/footer.tsx
  src/components/common/FloatingBox/TabletComponents/header.tsx
  src/components/common/FloatingBox/TabletComponents/main.tsx
  src/components/common/FloatingBox/desktop.tsx
  src/components/common/FloatingBox/mobile.tsx
  src/components/common/Modal/DateSelect/footer.tsx
  src/components/common/Modal/DateSelect/header.tsx
  src/components/common/Modal/DateSelect/index.tsx
  src/components/common/Pagination/index.tsx
  src/components/common/ReservationScheduleSelect/index.tsx
  src/components/pages/ActivityDetails/activityInformation.tsx
  src/components/pages/ActivityDetails/header.tsx
  src/hooks/useReservationMutation.ts
  src/store/activityDetailsAtom.ts
Labels: Refactor

#54 Fix: 로그인 에러 해결
  src/components/common/Input/DefaultInput.tsx
Labels: Fix

#55 Feat: 체험 상세 페이지 기능 추가
  src/apis/ActivityDetailsPage/deleteActivity.ts
  src/apis/ActivityDetailsPage/getActivityAvailableSchedule.ts
  src/apis/ActivityDetailsPage/getActivityDetailsData.ts
  src/apis/ActivityDetailsPage/getActivityReviewList.ts
  src/apis/ActivityDetailsPage/getMyInformation.ts
  src/apis/ActivityDetailsPage/postActivityReservation.ts
  src/apis/activityDetails.ts
  src/components/common/FloatingBox/TabletComponents/main.tsx
  src/components/common/FloatingBox/desktop.tsx
  src/components/common/FloatingBox/mobile.tsx
  src/components/common/ReservationScheduleSelect/index.tsx
  src/components/pages/ActivityDetails/activityInformation.tsx
  src/components/pages/ActivityDetails/header.tsx
  src/components/pages/ActivityDetails/reviewList.tsx
  src/hooks/useActivityData.tsx
  src/types/activity.ts
Labels: Feat

#56 Feat: 체험 상세 페이지: 예약하기 버튼 클릭시 성공, 에러 상태에 따른 모달 렌더링 기능 추가
  src/apis/ActivityDetailsPage/deleteActivity.ts
  src/apis/ActivityDetailsPage/postActivityReservation.ts
  src/components/common/FloatingBox/TabletComponents/main.tsx
  src/components/common/FloatingBox/desktop.tsx
  src/components/common/FloatingBox/mobile.tsx
  src/components/common/FloatingBox/tablet.tsx
  src/components/pages/ActivityDetails/activityInformation.tsx
  src/components/pages/ActivityDetails/reviewList.tsx
  src/components/pages/ActivityDetails/useReservationSubmit.ts
  src/constants/errorMessages.ts
Labels: Feat

#57 Feat: my page api
  package-lock.json
  package.json
  public/assets/images/profile-image.png
  src/apis/getUserProfile.ts
  src/apis/updateProfile.ts
  src/apis/uploadImage.ts
  src/components/common/NavBar/index.tsx
  src/components/common/SideNavMenu/sideNavMenuProfile.tsx
  src/components/pages/myPage/Schedule/mySchedule.tsx
  src/components/pages/myPage/inputSection.tsx
  src/components/pages/myPage/myProfile.tsx
  src/components/pages/myPage/passwordInputSection.tsx
  src/store/userAtom.ts
  src/utils/formatDate.ts
Labels: Feat

#58 Feat: 내 체험 관리 페이지 api 연동
  src/apis/myPage/myActivitySettings.ts
  src/apis/myPage/myActivitySettings.types.ts
  src/components/common/Cards/components/cardFooter.tsx
  src/components/common/Cards/hooks/useDeleteActivityMutation.ts
  src/components/common/Cards/myActivityCard.tsx
  src/components/common/Input/DateInput/customInput.tsx
  src/components/common/Input/DateInput/dateInput.tsx
  src/components/common/Input/DefaultInput.tsx
  src/components/common/Input/DropdownInput/dropdownInput.tsx
  src/components/common/Input/DropdownInput/dropdownInputList.tsx
  src/components/common/SideNavMenu/sideNavMenuOptionList.tsx
  src/components/pages/ActivityDetails/review.tsx
  src/components/pages/myPage/ActivitySettings/activitySettingsContent.tsx
  src/components/pages/myPage/ActivitySettings/hooks/useActivitiesQuery.ts
  src/components/pages/myPage/ActivitySettings/myActivityCardList.tsx
  src/components/pages/myPage/ActivitySettings/types/activitySettingsContent.types.ts
  src/components/pages/myPage/ActivitySettings/types/myActivityCardList.types.ts
  src/components/pages/myPage/RegistActivity/addActivityTimeSection.tsx
  src/components/pages/myPage/RegistActivity/addressInputSection.tsx
  src/components/pages/myPage/RegistActivity/hooks/useActivityByIdQuery.ts
  src/components/pages/myPage/RegistActivity/hooks/useActivityMutation.ts
  src/components/pages/myPage/RegistActivity/hooks/useUploadBannerImageMutation.ts
  src/components/pages/myPage/RegistActivity/hooks/useUploadIntroImageMutation.ts
  src/components/pages/myPage/RegistActivity/imageUploadSection.tsx
  src/components/pages/myPage/RegistActivity/registActivityContent.tsx
  src/components/pages/myPage/RegistActivity/scheduleItem.tsx
  src/components/pages/myPage/RegistActivity/types/addActivityTimeSection.types.ts
  src/components/pages/myPage/RegistActivity/types/addressInputSection.types.ts
  src/components/pages/myPage/RegistActivity/types/registActivityContent.types.ts
  src/components/pages/myPage/RegistActivity/types/uploadImageSection.types.ts
  src/components/pages/myPage/RegistActivity/uploadBannerImageSection.tsx
  src/components/pages/myPage/RegistActivity/uploadIntroImageSection.tsx
  src/constants/registAcitivtyErrorMessages.js
  src/hooks/useIntersectionObserver.ts
  src/libs/axios.ts
  src/mockData/myActivityCardsData.ts
  src/pages/_app.tsx
  src/pages/my-page/activity-settings.tsx
  src/pages/my-page/regist-activity/[activity-id]/index.tsx
  src/pages/my-page/regist-activity/index.tsx
  src/stories/Cards/myActivityCard.stories.tsx
  src/types/cardDataList.ts
  src/types/dateInput.ts
  src/types/dropDownInputTypes.ts
  src/types/regisActivity.ts
  src/utils/formatDate.ts
  src/utils/formatNumber.ts
  src/utils/schema.ts
Labels: Feat

#59 Refactor: 카카오 지도가 배포 환경에서 렌더링 되지 않는 현상 수정
  src/apis/ActivityDetailsPage/deleteActivity.ts
  src/apis/ActivityDetailsPage/postActivityReservation.ts
  src/components/common/Button/defaultButton.tsx
  src/components/common/FloatingBox/TabletComponents/main.tsx
  src/components/common/FloatingBox/desktop.tsx
  src/components/common/FloatingBox/mobile.tsx
  src/components/common/Input/DefaultInput.tsx
  src/components/common/Modal/RegisterConfirm/index.tsx
  src/components/pages/ActivityDetails/activityInformation.tsx
  src/components/pages/ActivityDetails/header.tsx
  src/components/pages/ActivityDetails/kakaoMap.tsx
  src/components/pages/ActivityDetails/review.tsx
  src/components/pages/ActivityDetails/reviewList.tsx
  src/components/pages/ActivityDetails/useReservationSubmit.ts
  src/pages/activities/index.tsx
  src/types/activity.ts
Labels: Refactor

#61 Feat: 예약 내역 페이지 필터 기능 구현
  src/apis/myPage/myReservations.ts
  src/apis/myPage/myReservations.types.ts
  src/apis/myPage/schedule.ts
  src/components/common/Cards/hooks/usePatchMyReservationMutation.ts
  src/components/common/Cards/reservationCard.tsx
  src/components/common/Filter/index.tsx
  src/components/common/Modal/CancelConfirm/index.tsx
  src/components/common/Modal/CancelReservation/index.tsx
  src/components/common/Modal/index.ts
  src/components/pages/myPage/ActivitySettings/activitySettingsContent.tsx
  src/components/pages/myPage/ActivitySettings/hooks/useActivitiesQuery.ts
  src/components/pages/myPage/ReservationList/hooks/useMyReservationsQuery.ts
  src/components/pages/myPage/ReservationList/reservationCardList.tsx
  src/components/pages/myPage/ReservationList/reservationContent.tsx
  src/pages/my-page/reservation-list.tsx
  src/store/reservationIdAtom.ts
  src/stories/Cards/reservationCard.stories.tsx
  src/stories/Filter/filter.stories.tsx
  src/stories/Modal/cancelReservation.stories.tsx
  src/utils/cardStatus.ts
Labels: Feat

#63 Feat: 예약 내역 페이지 리뷰(후기 작성) 기능
  src/apis/myPage/myReservations.ts
  src/components/common/Cards/reservationCard.tsx
  src/components/common/Modal/Review/hook/usePostReviewMutataion.ts
  src/components/common/Modal/Review/index.tsx
  src/components/common/Modal/Review/textareaWithSubmit.tsx
  src/pages/my-page/reservation-list.tsx
  src/store/completedReviewAtom.ts
  src/types/reviewModalTypes.ts
Labels: Feat

#62 Feat: 메타데이터 적용
  package-lock.json
  package.json
  src/components/common/Modal/RegisterConfirm/index.tsx
  src/components/pages/ActivityDetails/activityInformation.tsx
  src/components/pages/ActivityDetails/header.tsx
  src/components/pages/ActivityDetails/reviewList.tsx
  src/components/pages/ActivityDetails/scrollToTopButton.tsx
  src/components/pages/ActivityDetails/useReservationSubmit.ts
  src/pages/activities/index.tsx
Labels: Feat

#66 Feat: MainPage 구현
  public/assets/icons/right-arrow.svg
  src/apis/mainPage/activities.ts
  src/components/common/Search/index.tsx
  src/components/pages/main/ActivityCards.tsx
  src/components/pages/main/MainPage.tsx
  src/components/pages/main/PopularActivityCard.tsx
  src/components/pages/main/RadioTab/RadioTabContext.tsx
  src/components/pages/main/RadioTab/RadioTabItem.tsx
  src/components/pages/main/RadioTab/RadtioTabRoot.tsx
  src/components/pages/main/RadioTab/index.tsx
  src/components/pages/main/Swiper/SwiperContext.tsx
  src/components/pages/main/Swiper/SwiperRoot.tsx
  src/components/pages/main/Swiper/SwiperSlide.tsx
  src/components/pages/main/Swiper/SwiperTrigger.tsx
  src/components/pages/main/Swiper/index.tsx
  src/components/pages/main/mainPage.type.ts
  src/components/pages/main/useBackupImage.ts
Labels: Feat, Design

#64 Feat: 소셜 로그인, 네브바, 로그아웃
  src/apis/auth.ts
  src/apis/socialAuth.ts
  src/components/common/NavBar/index.tsx
  src/components/pages/auth/socialForm.tsx
  src/components/pages/auth/useGoogleAuth.ts
  src/components/pages/auth/useKakaoAuth.ts
  src/components/pages/auth/useSignin.ts
  src/components/pages/auth/useSignout.ts
  src/constants/errorMessages.ts
  src/constants/successMessages.ts
  src/libs/axios.ts
  src/pages/_app.tsx
  src/pages/social/google.tsx
  src/pages/social/kakao.tsx
  src/store/tokenAtom.ts
  src/types/auth.ts
  src/utils/getSocialToken.ts
Labels: Feat

#68 Feat: 체험 상세 페이지 추가 기능 구현
  package-lock.json
  package.json
  public/assets/icons/new-star.svg
  public/assets/icons/next-image-button.svg
  public/assets/icons/prev-image-button.svg
  public/assets/icons/share.svg
  src/apis/ActivityDetailsPage/deleteActivity.ts
  src/apis/ActivityDetailsPage/getActivityReviewList.ts
  src/apis/ActivityDetailsPage/getMyInformation.ts
  src/apis/ActivityDetailsPage/postActivityReservation.ts
  src/apis/ActivityDetailsPage/reviewList.ts
  src/components/common/FloatingBox/desktop.tsx
  src/components/common/ReservationScheduleSelect/index.tsx
  src/components/common/SideNavMenu/sideNavMenuOption.tsx
  src/components/pages/ActivityDetails/activityInformation.tsx
  src/components/pages/ActivityDetails/bannerImage.tsx
  src/components/pages/ActivityDetails/bannerImageModal.tsx
  src/components/pages/ActivityDetails/description.tsx
  src/components/pages/ActivityDetails/header.tsx
  src/components/pages/ActivityDetails/reviewList.tsx
  src/components/pages/ActivityDetails/useReservationSubmit.ts
  src/pages/activities/[activity-id]/index.tsx
  src/pages/activities/[activityId]/index.tsx
  src/pages/index.tsx
  src/types/activity.ts
  src/types/activityReviews.ts
  src/types/sideNavMenuTypes.ts
Labels: Feat

#69 Refactor: 내 체험 관리 페이지 리팩토링
  src/components/pages/myPage/ActivitySettings/activitySettingsContent.tsx
  src/components/pages/myPage/ActivitySettings/hooks/useActivitiesQuery.ts
  src/components/pages/myPage/RegistActivity/registActivityContent.tsx
  src/components/pages/myPage/ReservationList/reservationContent.tsx
  src/pages/my-page/activity-settings.tsx
  src/pages/my-page/regist-activity/[activity-id]/index.tsx
  src/pages/my-page/regist-activity/index.tsx
  src/pages/my-page/reservation-list.tsx
Labels: Refactor

#70 Refactor: 예약 현황 페이지, 내 정보 페이지 리팩토링
  src/components/common/Footer/index.tsx
  src/components/common/ReservationInfoModal/index.tsx
  src/components/pages/myPage/Schedule/calender.tsx
  src/components/pages/myPage/Schedule/dateCell.tsx
  src/components/pages/myPage/Schedule/mySchedule.tsx
  src/components/pages/myPage/inputSection.tsx
  src/components/pages/myPage/myProfile.tsx
  src/components/pages/myPage/passwordInputSection.tsx
  src/pages/my-page/profile.tsx
  src/pages/my-page/schedule.tsx
  src/styles/globals.css
Labels: Refactor

#71 Refactor: 로그인/회원가입 페이지 추가기능 및 리팩토링
  package-lock.json
  package.json
  public/assets/lotties/404page.json
  src/apis/socialAuth.ts
  src/components/common/NavBar/index.tsx
  src/components/pages/404/notFound.tsx
  src/components/pages/auth/signupForm.tsx
  src/components/pages/auth/terms.tsx
  src/components/pages/auth/useGoogleAuth.ts
  src/components/pages/auth/useKakaoAuth.ts
  src/components/pages/auth/useRandomNickname.ts
  src/components/pages/auth/useSignin.ts
  src/components/pages/auth/useSignout.ts
  src/hooks/useRedirectMessage.ts
  src/libs/axios.ts
  src/middleware.ts
  src/pages/404/index.tsx
  src/pages/_app.tsx
  src/types/auth.ts
  src/utils/calculatePassword.ts
  src/utils/schema.ts
Labels: Feat, Refactor

#72 Refactor: 배너 이미지 모달 수정, 캘린더 컴포넌트 수정
  src/components/common/Calendar/index.tsx
  src/components/common/FloatingBox/DesktopComponents/timeSlotSelection.tsx
  src/components/common/Modal/DateSelect/timeSlotSelection.tsx
  src/components/common/ReservationScheduleSelect/index.tsx
  src/components/pages/ActivityDetails/activityInformation.tsx
  src/components/pages/ActivityDetails/bannerImageModal.tsx
  src/components/pages/ActivityDetails/header.tsx
  src/types/availableSchedulesTypes.ts
Labels: Refactor

#75 Fix: 체험 상세 페이지 버그 수정
  src/components/common/FloatingBox/MobileComponents/priceInfo.tsx
  src/components/common/FloatingBox/mobile.tsx
  src/components/pages/ActivityDetails/activityInformation.tsx
  src/components/pages/ActivityDetails/bannerImageModal.tsx
  src/components/pages/ActivityDetails/reviewList.tsx
  src/components/pages/ActivityDetails/scrollToTopButton.tsx
Labels: Fix

#77 Refactor: 체험 상세 페이지 수정
  src/components/common/FloatingBox/tablet.tsx
  src/components/pages/ActivityDetails/activityInformation.tsx
  src/components/pages/ActivityDetails/bannerImage.tsx
  src/components/pages/ActivityDetails/description.tsx
  src/pages/activities/[activityId]/index.tsx
Labels: Refactor

#81 Refactor: 엑세스 토큰 로컬 스토리지에서 쿠키로 변경됨에 따라 토큰 불러오는 코드 수정
  src/components/pages/ActivityDetails/activityInformation.tsx
  src/components/pages/ActivityDetails/header.tsx
Labels: Refactor

#83 Feat: 리뷰 작성 모달 api 연동
  src/components/common/Cards/reservationCard.tsx
  src/components/common/Modal/Review/header.tsx
  src/components/pages/myPage/ReservationList/reservationCardList.tsx
  src/pages/my-page/reservation-list.tsx
  src/stories/Cards/reservationCard.stories.tsx
  src/types/reviewModalTypes.ts
Labels: Feat

#84 Refactor: 내 체험 관리 페이지 모바일 사이즈일 때 체험 등록하기 버튼 추가
  src/pages/my-page/activity-settings.tsx
Labels: Refactor
