Repository codeit-sprint6-team14/Global-Nomad, pull requests merged in 2024-07, with the labels that each got.

#1 Chore: 이슈 템플릿 추가
  .github/ISSUE_TEMPLATE/✨-feat.md
  .github/ISSUE_TEMPLATE/📦️-chore.md
  .github/ISSUE_TEMPLATE/🔨-refactor.md
  .github/ISSUE_TEMPLATE/🚑️-fix.md
Labels: Chore

#2 Chore: PR 템플릿 추가
  .github/pull_request_template.md
Labels: Chore

#4 Feat: footer
  .eslintrc.json
  .husky/prepare-commit-msg
  public/images/icon-facebook.svg
  public/images/icon-instagram.svg
  public/images/icon-twitter.svg
  public/images/icon-youtube.svg
  src/components/Footer/index.tsx
  src/pages/index.tsx
Labels: Feat

#6 Feat: Chip 공통 컴포넌트 개발
  .eslintrc.json
  public/fonts/PretendardVariable.woff2
  src/components/Chip/index.tsx
  src/components/common/dummy.txt
  src/pages/_app.tsx
  tailwind.config.ts
Labels: Feat

#9 Feat: 네비게이션바 UI(반응형까지 완료) 구현
  .eslintrc.json
  public/dummy.txt
  public/images/dummy.txt
  public/images/ic-bell.svg
  public/images/ic-test-profile.svg
  public/images/navbar-logo.svg
  src/components/NavBar/dropDown.tsx
  src/components/NavBar/index.tsx
  src/components/dummy.txt
  src/pages/index.tsx
  src/styles/globals.css
Labels: Feat

#7 Design: Category Button 공통 컴포넌트 UI 개발
  src/components/Category/index.tsx
Labels: Design

#10 Design: 버튼 공통 컴포넌트 UI 구현
  .prettierrc
  package-lock.json
  package.json
  src/components/Button/index.tsx
  src/components/Category/index.tsx
  src/components/Filter/index.tsx
Labels: Design

#11 Design: 기본 Input 및 비밀번호 Input 구현
  public/images/icon-visibility-off.svg
  public/images/icon-visibility-on.svg
  src/components/Input/DefaultInput.tsx
  src/components/Input/PasswordInput.tsx
  src/components/Input/index.ts
Labels: Design

#12 Design: 사이드 네이게이션 바 UI(반응형까지 완료) 구현
  public/images/icon-bell.svg
  public/images/icon-booking-history.svg
  public/images/icon-booking-status.svg
  public/images/icon-my-information.svg
  public/images/icon-pencil.svg
  public/images/icon-setting.svg
  public/images/icon-test-profile.svg
  public/images/test-profile-img.png
  src/components/NavBar/index.tsx
  src/components/SideNavMenu/index.tsx
  src/components/SideNavMenu/menuOptionList.tsx
  src/components/SideNavMenu/sideNavMenu.tsx
  src/components/SideNavMenu/sideNavMenuOption.tsx
  src/components/SideNavMenu/sideNavMenuOptionList.tsx
  src/pages/index.tsx
  src/stories/Page.tsx
  src/types/SideNavMenuOption.ts
  src/types/dummy.txt
Labels: Design

#13 Fp 12 feat/pagination
  .prettierrc
  src/components/Footer/index.tsx
  src/components/Pagination/index.tsx
  src/pages/index.tsx
Labels: Design

#15 Refactor: button 공통 컴포넌트 리팩토링
  package-lock.json
  package.json
  src/components/Button/index.tsx
Labels: Refactor

#14 Refactor: sideNavMenu.tsx 내부 로직 index.tsx로 이동
  .eslintrc.json
  .github/ISSUE_TEMPLATE/✨-feat.md
  .github/ISSUE_TEMPLATE/📦️-chore.md
  .github/ISSUE_TEMPLATE/🔨-refactor.md
  .github/ISSUE_TEMPLATE/🚑️-fix.md
  .prettierrc
  .storybook/main.ts
  .storybook/preview.ts
  next.config.mjs
  package-lock.json
  postcss.config.mjs
  public/images/icon-booking-status.svg
  public/images/icon-pencil.svg
  src/components/Button/index.tsx
  src/components/Category/index.tsx
  src/components/Chip/index.tsx
  src/components/Filter/index.tsx
  src/components/Footer/index.tsx
  src/components/Input/DefaultInput.tsx
  src/components/Input/PasswordInput.tsx
  src/components/Input/index.ts
  src/components/NavBar/dropDown.tsx
  src/components/NavBar/index.tsx
  src/components/SideNavMenu/index.tsx
  src/components/SideNavMenu/menuOptionList.tsx
  src/components/SideNavMenu/sideNavMenu.tsx
  src/components/SideNavMenu/sideNavMenuOption.tsx
  src/components/SideNavMenu/sideNavMenuOptionList.tsx
  src/components/SideNavMenu/sideNavMenuProfile.tsx
  src/pages/_app.tsx
  src/pages/_document.tsx
  src/pages/index.tsx
  src/stories/Button.stories.ts
  src/stories/Button.tsx
  src/stories/Configure.mdx
  src/stories/Header.stories.ts
  src/stories/Header.tsx
  src/stories/Page.stories.ts
  src/stories/Page.tsx
  src/types/SideNavMenuOption.ts
  tailwind.config.ts
Labels: Refactor

#16 Design: Dropdown Input, Date Input 컴포넌트 구현
  package-lock.json
  package.json
  public/images/icon-arrow-dropdown.svg
  public/images/icon-calendar.svg
  public/images/icon-checked.svg
  src/components/Button/index.tsx
  src/components/Footer/index.tsx
  src/components/Input/DateInput.tsx
  src/components/Input/DropDownInput.tsx
  src/components/Input/index.ts
  src/components/Pagination/index.tsx
Labels: Design

#17 Design: Date Select 모달 공통 컴포넌트 UI 개발
  .prettierrc
  package-lock.json
  package.json
  public/svgs/ic-close-button.svg
  public/svgs/ic-down-arrow.svg
  public/svgs/ic-next-button.svg
  public/svgs/ic-prev-button.svg
  src/components/Button/categoryButton.tsx
  src/components/Button/defaultButton.tsx
  src/components/Button/index.tsx
  src/components/Calendar/body.tsx
  src/components/Calendar/header.tsx
  src/components/Calendar/index.tsx
  src/components/Category/index.tsx
  src/components/Chip/index.tsx
  src/components/Footer/index.tsx
  src/components/Icons/close.tsx
  src/components/Icons/index.ts
  src/components/Input/DateInput.tsx
  src/components/Input/DefaultInput.tsx
  src/components/Input/DropDownInput.tsx
  src/components/Input/PasswordInput.tsx
  src/components/Modal/dateSelectModal.tsx
  src/components/Modal/index.ts
  src/components/NavBar/index.tsx
  src/components/Pagination/index.tsx
  src/components/SideNavMenu/sideNavMenuOption.tsx
  src/components/SideNavMenu/sideNavMenuOptionList.tsx
  src/components/SideNavMenu/sideNavMenuProfile.tsx
  src/constants/date.ts
  src/constants/dummy.txt
  src/mockData/availableSchedule.js
  src/stories/Button.tsx
  src/stories/Header.tsx
  src/stories/Page.tsx
  src/types/availableSchedulesTypes.ts
  src/types/buttonTypes.ts
  src/types/calendarTypes.ts
  tailwind.config.ts
Labels: Design

#20 Design:card resource 디자인
  .eslintrc.json
  next.config.mjs
  package-lock.json
  package.json
  public/images/star.svg
  src/components/CardResource/index.tsx
  src/components/CardResource/popularExperienceCard.tsx
  src/components/CardResource/standardExperienceCard.tsx
  src/pages/index.tsx
Labels: Design

#24 Design: 공통 드롭다운 구현
  public/images/testImg/test-profile-img.png
  public/svgs/icon-bell.svg
  public/svgs/icon-booking-history.svg
  public/svgs/icon-booking-status.svg
  public/svgs/icon-kebab.svg
  public/svgs/icon-my-information.svg
  public/svgs/icon-pencil.svg
  public/svgs/icon-setting.svg
  public/svgs/icon-star.svg
  public/svgs/icon-test-profile.svg
  public/svgs/navbar-logo.svg
  src/components/Cards/cardFooter.tsx
  src/components/Cards/components/cardFooter.tsx
  src/components/Cards/components/cardHeader.tsx
  src/components/Cards/myActivityCard.tsx
  src/components/Cards/myActivityCardList.tsx
  src/components/Cards/reservationCard.tsx
  src/components/Dropdown/dropDownList.tsx
  src/components/Dropdown/dropDownOption.tsx
  src/components/Dropdown/index.tsx
  src/components/Input/DropDownInput.tsx
  src/components/NavBar/dropDown.tsx
  src/components/NavBar/index.tsx
  src/components/SideNavMenu/menuOptionList.tsx
  src/components/SideNavMenu/sideNavMenuProfile.tsx
  src/mockData/reservationCardsData.ts
  src/pages/index.tsx
  src/utils/cardStatus.ts
Labels: Design

#22 Design: 후기 작성 모달 UI 구현
  package-lock.json
  public/images/icon-close.svg
  public/images/icon-star-filled.svg
  public/images/icon-star.svg
  src/components/Modal/Review/header.tsx
  src/components/Modal/Review/index.tsx
  src/components/Modal/Review/starRating.tsx
  src/components/Modal/Review/textareaWithSubmit.tsx
  src/components/Modal/index.ts
  src/mockData/reviewData.ts
  src/types/reviewModalTypes.ts
Labels: Design

#26 Refactor: 버튼 공통 컴포넌트 리팩토링 v2
  src/components/Button/baseButton.tsx
  src/components/Button/categoryButton.tsx
  src/components/Button/defaultButton.tsx
  src/components/Button/index.tsx
  src/pages/index.tsx
  src/types/buttonTypes.ts
Labels: Refactor

#25 Refactor: 카드 리소스 리팩토링
  public/svgs/icon-facebook.svg
  public/svgs/icon-instagram.svg
  public/svgs/icon-twitter.svg
  public/svgs/icon-youtube.svg
  public/svgs/star.svg
  src/components/CardResource/index.tsx
  src/components/CardResource/popularExperienceCard.tsx
  src/components/CardResource/price.tsx
  src/components/CardResource/rating.tsx
  src/components/CardResource/standardExperienceCard.tsx
  src/components/Footer/index.tsx
  src/types/cardResourceTypes.ts
Labels: Refactor
